CREATE TABLE IF NOT EXISTS tournaments (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  sport VARCHAR(80) NOT NULL,
  location VARCHAR(120) NOT NULL,
  rules TEXT NOT NULL,
  format VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'open',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);